apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: devops03acr.azurecr.io/app-api:1.1.0
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/realworld?schema=public
            - name: JWT_SECRET
              value: dev-secret
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3000"
            - name: OTEL_SERVICE_NAME
              value: realworld-api
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://my-opentelemetry-collector.hackathon-2026.svc.cluster.local:4318/v1/traces
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
